name: scriptsanalyze
description: WebRTC 영상통화 & 대화 분석 앱

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.13.1
  webrtc_interface: ^1.2.2
  record: ^6.0.0
  http: ^1.1.0
  dio: ^5.3.3
  path_provider: ^2.1.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  flutter_dotenv: ^5.1.0
  intl: ^0.20.2
  permission_handler: ^11.4.0
  provider: ^6.0.5
  uuid: ^4.5.1
  device_info_plus: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env