// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGkewT26u2EyibVwJJqtT1nyi4OQQBvnU',
    appId: '1:1072939088194:web:d753cb3610e8ee6ed870db',
    messagingSenderId: '1072939088194',
    projectId: 'blinddate-273e5',
    authDomain: 'blinddate-273e5.firebaseapp.com',
    storageBucket: 'blinddate-273e5.firebasestorage.app',
    measurementId: 'G-LV33624KZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaAbB_TbbFY-PLj0DAolyCXiEGGbOIiWc',
    appId: '1:1072939088194:android:2347f1f8ab85f757d870db',
    messagingSenderId: '1072939088194',
    projectId: 'blinddate-273e5',
    storageBucket: 'blinddate-273e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM0MTQmX_APThN-A6oEblsHZ44o6ZLIcI',
    appId: '1:1072939088194:ios:3f39cb3f5ba4106ad870db',
    messagingSenderId: '1072939088194',
    projectId: 'blinddate-273e5',
    storageBucket: 'blinddate-273e5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM0MTQmX_APThN-A6oEblsHZ44o6ZLIcI',
    appId: '1:1072939088194:ios:3f39cb3f5ba4106ad870db',
    messagingSenderId: '1072939088194',
    projectId: 'blinddate-273e5',
    storageBucket: 'blinddate-273e5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGkewT26u2EyibVwJJqtT1nyi4OQQBvnU',
    appId: '1:1072939088194:web:cdc5180cc20a18bdd870db',
    messagingSenderId: '1072939088194',
    projectId: 'blinddate-273e5',
    authDomain: 'blinddate-273e5.firebaseapp.com',
    storageBucket: 'blinddate-273e5.firebasestorage.app',
    measurementId: 'G-JRXNWZFVHT',
  );
}
